name: Build Minecraft server

on:
  push:
    branches:
      - master

jobs:
  build-minecraft:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Minecraft server build
        run: |
          curl -v -XPOST -u "${{ secrets.ACTIONS_USER}}:${{secrets.ACTIONS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/MinecraftAuthentication/minecraft/dispatches --data '{"event_type": "build_application"}'
